# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :servidorWeb do |servidorWeb|
    servidorWeb.vm.box = "bento/ubuntu-22.04"
    servidorWeb.vm.network :private_network, ip: "192.168.80.3"
    
    servidorWeb.vm.provision "file", source: "frontend", destination: "/home/vagrant/frontend"
    servidorWeb.vm.provision "file", source: "microUsers", destination: "/home/vagrant/microUsers"
    servidorWeb.vm.provision "file", source: "microProducts", destination: "/home/vagrant/microProducts"
    servidorWeb.vm.provision "file", source: "init.sql", destination: "/home/vagrant/init.sql"

    servidorWeb.vm.provision "shell", path: "script.sh"

    # Agregamos un nuevo provisioner para instalar Consul
    servidorWeb.vm.provision "shell", inline: <<-SHELL
      echo "Instalando Consul..."
      sudo apt-get update -y
      sudo apt-get install -y unzip

      # Descarga e instalación de Consul (versión de ejemplo 1.14.5)
      wget -q https://releases.hashicorp.com/consul/1.14.5/consul_1.14.5_linux_amd64.zip
      unzip consul_1.14.5_linux_amd64.zip
      sudo mv consul /usr/local/bin/
      rm consul_1.14.5_linux_amd64.zip

      # Verificar la instalación
      consul --version

      echo "Consul instalado con éxito."
    SHELL

    servidorWeb.vm.hostname = "servidorWeb"
  end
end
